version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: ModulBank/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=modulbank_db;Username=postgres;Password=postgres
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=modulbank_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 